apiVersion: v1
kind: ServiceAccount
metadata:
  name: team-a-developer
  namespace: team-a
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: team-a-developer
  namespace: team-a
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: team-a-developer
  namespace: team-a
subjects:
  - kind: ServiceAccount
    name: team-a-developer
    namespace: team-a
roleRef:
  kind: Role
  name: team-a-developer
  apiGroup: rbac.authorization.k8s.io