# ==========================================
# Build stage
# ==========================================
FROM maven:3.9.16-eclipse-temurin-21 AS build

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline -B

COPY src ./src

RUN mvn clean package -DskipTests


# ==========================================
# Runtime stage
# ==========================================
FROM eclipse-temurin:21-jre

WORKDIR /app

RUN useradd --system --create-home --uid 10001 appuser

COPY --from=build /app/target/order-consumer-0.0.1-SNAPSHOT.jar app.jar

USER 10001

ENTRYPOINT ["java", "-jar", "app.jar"]