apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-stack
  namespace: argocd

spec:
  project: default

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 88.6.1
      helm:
        releaseName: observability-stack
        valueFiles:
          - $values/infrastructure/observability/kube-prometheus-stack/values.yaml

    - repoURL: https://github.com/leoviana00/kube-dev-guardian.git
      targetRevision: FEATURE06-OBSERVABILITY
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true